@Rainfall.API_HostAddress = https://localhost:7203

GET {{Rainfall.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Rainfall.API_HostAddress}}/api/rainfall/id/1/readings?count=100
Accept: application/json
###
